---
- name: Install and Configure HTTPD Web Server
  hosts: all
  remote_user: ec2-user
  become: yes  # To run tasks with sudo

  tasks:
    - name: Install HTTPD package
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Ensure HTTPD is enabled and running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy a custom index.html file
      ansible.builtin.copy:
        src: /home/ec2-user/index.html
        dest: /var/www/html/index.html
        mode: '777'

    - name: Open HTTP port in the firewall
      ansible.builtin.firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Restart HTTPD to apply changes
      ansible.builtin.service:
        name: httpd
        state: restarted

