---
- hosts: jenkins
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Add repository jenkins
      yum_repository:
        name: jenkins
        description: jen YUM repository
        baseurl: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    - name : install the latest version of java & jenkins
      yum:
        name: "{{item}}"
        state: present
      loop:
        - java
        - jenkins
    - name : start service jenkins, if not started
      service:
        name: jenkins
        state: started
    - name: Update Jenkins port in /etc/sysconfig/jenkins
      lineinfile:
        path:  /lib/systemd/system/jenkins.service
        regexp: '^JENKINS_PORT='
        line: 'JENKINS_PORT=9090'
        create: yes
    - handlers:
    - name: restart jenkins
      service:
        name: jenkins
        state: restarted
            
